## Load csv data

In [6]:
import numpy as np
import pandas as pd
df = pd.read_csv('./loans_data.csv')
df

safe_loans grade  sub_grade_num  short_emp  emp_length_num  \
0               1     B            0.6          0              11   
1               1     B            0.2          0               3   
2               1     B            0.6          1               1   
3               1     A            0.8          0               6   
4               1     C            1.0          0               8   
5               1     B            0.4          0              11   
6               1     B            0.8          0               2   
7               1     A            0.4          0               6   
8               1     B            0.2          0               2   
9               1     B            0.4          0               3   
10              1     B            0.4          0               8   
11              1     C            0.4          0               5   
12              1     C            0.6          0               3   
13              1     D            0.2          0              10   
14              1     B            0.6          0               5   
15              1     A            0.2          0              11   
16              1     A            1.0          0               9   
17              1     C            0.2          0               6   
18              1     A            1.0          0               7   
19              1     A            0.8          0              11   
20              1     C            0.4          0               8   
21              1     A            0.6          0               6   
22              1     C            0.6          0               3   
23              1     B            0.2          0               8   
24              1     D            0.2          0               6   
25              1     B            0.2          0               3   
26              1     C            0.4          0              11   
27              1     C            0.2          0               3   
28              1     B            0.8          0               6   
29              1     B            0.4          0               4   
...           ...   ...            ...        ...             ...   
46473          -1     D            0.2          0              10   
46474          -1     C            0.6          0              11   
46475          -1     B            0.4          0              11   
46476          -1     C            0.6          0              11   
46477          -1     D            0.8          0               8   
46478          -1     F            0.6          0              11   
46479          -1     D            0.2          0              10   
46480          -1     B            0.2          0              11   
46481          -1     C            0.2          1               0   
46482          -1     B            0.8          0              11   
46483          -1     E            1.0          0               7   
46484          -1     D            0.2          0              11   
46485          -1     C            0.4          0               2   
46486          -1     D            0.8          0               6   
46487          -1     D            0.2          0               3   
46488          -1     C            0.4          0              11   
46489          -1     C            0.2          0               2   
46490          -1     B            0.6          1               0   
46491          -1     A            0.8          0               7   
46492          -1     B            0.4          0              11   
46493          -1     B            1.0          0               2   
46494          -1     C            0.8          1               1   
46495          -1     C            0.6          0               9   
46496          -1     B            1.0          1               1   
46497          -1     C            0.6          1               1   
46498          -1     D            0.2          0              11   
46499

## Map string to number

In [7]:
grade_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7}
home_map = {'MORTGAGE': 1, 'OTHER': 2, 'OWN': 3, 'RENT': 4}
purpose_map = {'car': 1, 'credit_card': 2, 'debt_consolidation': 3, 'home_improvement': 4, 'house': 5, 'major_purchase': 6, 'medical': 7, 'moving': 8, 'other': 9, 'small_business': 10, 'vacation': 11, 'wedding': 12}

df = df.replace({'grade': grade_map, 'home_ownership': home_map, 'purpose': purpose_map})
df

safe_loans  grade  sub_grade_num  short_emp  emp_length_num  \
0               1      2            0.6          0              11   
1               1      2            0.2          0               3   
2               1      2            0.6          1               1   
3               1      1            0.8          0               6   
4               1      3            1.0          0               8   
5               1      2            0.4          0              11   
6               1      2            0.8          0               2   
7               1      1            0.4          0               6   
8               1      2            0.2          0               2   
9               1      2            0.4          0               3   
10              1      2            0.4          0               8   
11              1      3            0.4          0               5   
12              1      3            0.6          0               3   
13              1      4            0.2          0              10   
14              1      2            0.6          0               5   
15              1      1            0.2          0              11   
16              1      1            1.0          0               9   
17              1      3            0.2          0               6   
18              1      1            1.0          0               7   
19              1      1            0.8          0              11   
20              1      3            0.4          0               8   
21              1      1            0.6          0               6   
22              1      3            0.6          0               3   
23              1      2            0.2          0               8   
24              1      4            0.2          0               6   
25              1      2            0.2          0               3   
26              1      3            0.4          0              11   
27              1      3            0.2          0               3   
28              1      2            0.8          0               6   
29              1      2            0.4          0               4   
...           ...    ...            ...        ...             ...   
46473          -1      4            0.2          0              10   
46474          -1      3            0.6          0              11   
46475          -1      2            0.4          0              11   
46476          -1      3            0.6          0              11   
46477          -1      4            0.8          0               8   
46478          -1      6            0.6          0              11   
46479          -1      4            0.2          0              10   
46480          -1      2            0.2          0              11   
46481          -1      3            0.2          1               0   
46482          -1      2            0.8          0              11   
46483          -1      5            1.0          0               7   
46484          -1      4            0.2          0              11   
46485          -1      3            0.4          0               2   
46486          -1      4            0.8          0               6   
46487          -1      4            0.2          0               3   
46488          -1      3            0.4          0              11   
46489          -1      3            0.2          0               2   
46490          -1      2            0.6          1               0   
46491          -1      1            0.8          0               7   
46492          -1      2            0.4          0              11   
46493          -1      2            1.0          0               2   
46494          -1      3            0.8          1               1   
46495          -1      3            0.6          0               9   
46496          -1      2            1.0          1               1   
46497          -1      3            0.6          1               1   
46498          -1

## Split features, target and labels

In [8]:
features = np.array(df.iloc[:, 1:])
target = np.array(df.iloc[:, 0])
labels = np.array(list(df))

## Normalize and binning to continuous data

In [9]:
def binning(arr):
    ret = []
    for x in arr:
        ret.append(round(x, 1))
    return ret

from sklearn import preprocessing
fix_list = [6, 8, 14, 17, 18, 19, 20, 21, 22, 23]
features[:, fix_list] = preprocessing.scale(features[:, fix_list])
for x in fix_list:
    features[:, x] = binning(features[:, x])
features

array([[ 2. ,  0.6,  0. , ..., -0.4, -0.3, -0.3],
       [ 2. ,  0.2,  0. , ...,  0.2,  0.3,  0.3],
       [ 2. ,  0.6,  1. , ..., -0.6, -0.5, -0.5],
       ..., 
       [ 5. ,  1. ,  1. , ..., -0.9, -0.8, -1. ],
       [ 4. ,  0.6,  0. , ..., -0.6, -0.5, -0.8],
       [ 4. ,  1. ,  0. , ...,  1.1,  1.1,  0.7]])

## Define functions to validate

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import KFold
# import pydotplus

def valid(clf):
    print("- Resubstitution validation")
    resub(clf)
    print("- K-fold cross validation")
    kfold(clf)

def accurancy(mat):
    return np.trace(mat) / np.sum(mat)

def resub(clf):
    global features, target
    X = features
    y = target
    clf = clf.fit(X, y)
    pred = clf.predict(X)
    mat = confusion_matrix(y, pred)
    print("Confusion matrix:")
    print(mat)
    print("Accuracy score:")
    print(accurancy(mat))

def kfold(clf):
    global features, target
    X = features
    y = target
    mat = np.zeros((2, 2), dtype = 'i')
    kf = KFold(n_splits = 30, shuffle = True)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        clf = clf.fit(X_train, y_train)
        pred = clf.predict(X_test)
        tmp = confusion_matrix(y_test, pred, labels=[-1, 1])
        mat += tmp
    print("Confusion matrix:")
    print(mat)
    print("Accuracy score:")
    print(accurancy(mat))
    return mat

def picout(clf, filename):
    global labels
    dot_data = tree.export_graphviz(clf, out_file = None, feature_names = labels, class_names = ['save', 'unsave'], filled = True)
    graph = pydotplus.graph_from_dot_data(dot_data)
    graph.write_png(filename + ".png")

## Decision Tree Classifier

In [11]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth = 10)
valid(clf)

- Resubstitution validation
Confusion matrix:
[[15708  7439]
 [ 6839 16517]]
Accuracy score:
0.692966045201
- K-fold cross validation
Confusion matrix:
[[14571  8576]
 [ 7891 15465]]
Accuracy score:
0.645893813302


## Gradient Boosting Classifier

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(max_depth = 9, max_features = 23, min_samples_split = 35)
valid(clf)

- Resubstitution validation
Confusion matrix:
[[18848  4299]
 [ 3998 19358]]
Accuracy score:
0.82158140335
- K-fold cross validation
Confusion matrix:
[[15821  7326]
 [ 7471 15885]]
Accuracy score:
0.681805474916


## Bagging Classifier

In [13]:
from sklearn.ensemble import BaggingClassifier
clf = BaggingClassifier(n_estimators = 30)
valid(clf)

- Resubstitution validation
Confusion matrix:
[[23136    11]
 [   27 23329]]
Accuracy score:
0.999182848418
- K-fold cross validation
Confusion matrix:
[[15878  7269]
 [ 8663 14693]]
Accuracy score:
0.657398447412


## Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(min_samples_split = 400)
valid(clf)

- Resubstitution validation
Confusion matrix:
[[15865  7282]
 [ 7715 15641]]
Accuracy score:
0.677504677118
- K-fold cross validation
Confusion matrix:
[[15392  7755]
 [ 8158 15198]]
Accuracy score:
0.657807023203
