In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataFrame = pd.read_csv("loans_data.csv")

In [4]:
dataFrame

safe_loans grade  sub_grade_num  short_emp  emp_length_num  \
0               1     B            0.6          0              11   
1               1     B            0.2          0               3   
2               1     B            0.6          1               1   
3               1     A            0.8          0               6   
4               1     C            1.0          0               8   
5               1     B            0.4          0              11   
6               1     B            0.8          0               2   
7               1     A            0.4          0               6   
8               1     B            0.2          0               2   
9               1     B            0.4          0               3   
10              1     B            0.4          0               8   
11              1     C            0.4          0               5   
12              1     C            0.6          0               3   
13              1     D            0.2          0              10   
14              1     B            0.6          0               5   
15              1     A            0.2          0              11   
16              1     A            1.0          0               9   
17              1     C            0.2          0               6   
18              1     A            1.0          0               7   
19              1     A            0.8          0              11   
20              1     C            0.4          0               8   
21              1     A            0.6          0               6   
22              1     C            0.6          0               3   
23              1     B            0.2          0               8   
24              1     D            0.2          0               6   
25              1     B            0.2          0               3   
26              1     C            0.4          0              11   
27              1     C            0.2          0               3   
28              1     B            0.8          0               6   
29              1     B            0.4          0               4   
...           ...   ...            ...        ...             ...   
46473          -1     D            0.2          0              10   
46474          -1     C            0.6          0              11   
46475          -1     B            0.4          0              11   
46476          -1     C            0.6          0              11   
46477          -1     D            0.8          0               8   
46478          -1     F            0.6          0              11   
46479          -1     D            0.2          0              10   
46480          -1     B            0.2          0              11   
46481          -1     C            0.2          1               0   
46482          -1     B            0.8          0              11   
46483          -1     E            1.0          0               7   
46484          -1     D            0.2          0              11   
46485          -1     C            0.4          0               2   
46486          -1     D            0.8          0               6   
46487          -1     D            0.2          0               3   
46488          -1     C            0.4          0              11   
46489          -1     C            0.2          0               2   
46490          -1     B            0.6          1               0   
46491          -1     A            0.8          0               7   
46492          -1     B            0.4          0              11   
46493          -1     B            1.0          0               2   
46494          -1     C            0.8          1               1   
46495          -1     C            0.6          0               9   
46496          -1     B            1.0          1               1   
46497          -1     C            0.6          1               1   
46498          -1     D            0.2          0              11   
46499

In [5]:
ColumnLabels = np.array(list(dataFrame))
Train_Matrix = np.matrix(dataFrame.iloc[:, 1:])
Target_Vector = np.array(dataFrame.iloc[:,0])

In [6]:
Grade = Train_Matrix[:, 0]
Grade

matrix([['B'],
        ['B'],
        ['B'],
        ..., 
        ['E'],
        ['D'],
        ['D']], dtype=object)

In [7]:
home_ownership = Train_Matrix[:, 4]
home_ownership

matrix([['OWN'],
        ['MORTGAGE'],
        ['RENT'],
        ..., 
        ['MORTGAGE'],
        ['MORTGAGE'],
        ['MORTGAGE']], dtype=object)

In [8]:
purpose = Train_Matrix[:, 6]
purpose

matrix([['credit_card'],
        ['credit_card'],
        ['credit_card'],
        ..., 
        ['medical'],
        ['medical'],
        ['debt_consolidation']], dtype=object)

## Using 1 of K method to replace categorial feature

In [9]:
Clean_Matrix = np.delete(Train_Matrix, [0, 4, 6], 1)
Clean_Matrix

matrix([[0.6, 0, 11, ..., 10000, 10000, 330.76],
        [0.2, 0, 3, ..., 15000, 15000, 483.38],
        [0.6, 1, 1, ..., 8500, 8500, 281.15],
        ..., 
        [1.0, 1, 0, ..., 6000, 6000, 170.53],
        [0.6, 0, 6, ..., 8525, 8525, 217.65],
        [1.0, 0, 11, ..., 22000, 22000, 582.5]], dtype=object)

## Clean Grade Field Ex: A =>(1,0,0,0,0,0,0)

In [10]:
def clean_grade(grade_matrix):
    new_matrix = np.zeros(shape=(grade_matrix.shape[0], 7))
    for row_number in range(len(grade_matrix)):
        symbol = grade_matrix[row_number, 0]
        arr = np.zeros(7)
        arr[ord(symbol) - ord('A')] = 1
        new_matrix[row_number, :] = arr
    return new_matrix
Clean_Grade_Matrix = clean_grade(Grade)

In [11]:
new_matrix = np.hstack((Clean_Matrix,Clean_Grade_Matrix))
print(Clean_Matrix.shape)
print(new_matrix.shape)
new_matrix

(46503, 21)
(46503, 28)


matrix([[0.6, 0, 11, ..., 0.0, 0.0, 0.0],
        [0.2, 0, 3, ..., 0.0, 0.0, 0.0],
        [0.6, 1, 1, ..., 0.0, 0.0, 0.0],
        ..., 
        [1.0, 1, 0, ..., 1.0, 0.0, 0.0],
        [0.6, 0, 6, ..., 0.0, 0.0, 0.0],
        [1.0, 0, 11, ..., 0.0, 0.0, 0.0]], dtype=object)

In [12]:
def clean_home_ownership(home_ownership_matrix):
    new_matrix = np.zeros(shape=(home_ownership_matrix.shape[0], 4))
    for row_number in range(len(home_ownership_matrix)):
        symbol = home_ownership_matrix[row_number, 0]
        arr = np.zeros(4)
        if symbol == 'OWN':
            arr[0] = 1
        elif symbol == 'MORTGAGE':
            arr[1] = 1
        elif symbol == 'RENT':
            arr[2] = 1
        elif symbol == 'OTHER':
            arr[3] = 1
        else:
            print(symbol)
        new_matrix[row_number, :] = arr
    return new_matrix
Clean_HomeOwnership_Matrix = clean_home_ownership(home_ownership)
# Clean_Grade_Matrix
new_matrix2 = np.hstack((new_matrix, Clean_HomeOwnership_Matrix))
new_matrix2

matrix([[0.6, 0, 11, ..., 0.0, 0.0, 0.0],
        [0.2, 0, 3, ..., 1.0, 0.0, 0.0],
        [0.6, 1, 1, ..., 0.0, 1.0, 0.0],
        ..., 
        [1.0, 1, 0, ..., 1.0, 0.0, 0.0],
        [0.6, 0, 6, ..., 1.0, 0.0, 0.0],
        [1.0, 0, 11, ..., 1.0, 0.0, 0.0]], dtype=object)

In [13]:
def clean_purpose(purpose_matrix):
    new_matrix = np.zeros(shape=(purpose_matrix.shape[0], 12))
    for row_number in range(len(purpose_matrix)):
        symbol = purpose_matrix[row_number, 0]
        arr = np.zeros(12)
        if symbol == 'credit_card':
            arr[0] = 1
        elif symbol == 'medical':
            arr[1] = 1
        elif symbol == 'debt_consolidation':
            arr[2] = 1
        elif symbol == 'car':
            arr[3] = 1
        elif symbol == 'small_business':
            arr[4] = 1
        elif symbol == 'home_improvement':
            arr[5] = 1
        elif symbol == 'vacation':
            arr[6] = 1
        elif symbol == 'major_purchase':
            arr[7] = 1
        elif symbol == 'moving':
            arr[8] = 1
        elif symbol == 'wedding':
            arr[9] = 1
        elif symbol == 'house':
            arr[10] = 1
        elif symbol == 'other':
            arr[11] = 1
        else:
            print(symbol)
        new_matrix[row_number, :] = arr
    return new_matrix
Clean_Purpose_Matrix = clean_purpose(purpose)
Final_Matrix = np.hstack((new_matrix2, Clean_HomeOwnership_Matrix))
Final_Matrix

matrix([[0.6, 0, 11, ..., 0.0, 0.0, 0.0],
        [0.2, 0, 3, ..., 1.0, 0.0, 0.0],
        [0.6, 1, 1, ..., 0.0, 1.0, 0.0],
        ..., 
        [1.0, 1, 0, ..., 1.0, 0.0, 0.0],
        [0.6, 0, 6, ..., 1.0, 0.0, 0.0],
        [1.0, 0, 11, ..., 1.0, 0.0, 0.0]], dtype=object)

### Final Matrix is the result using 1 of k method

In [14]:
Final_Matrix

matrix([[0.6, 0, 11, ..., 0.0, 0.0, 0.0],
        [0.2, 0, 3, ..., 1.0, 0.0, 0.0],
        [0.6, 1, 1, ..., 0.0, 1.0, 0.0],
        ..., 
        [1.0, 1, 0, ..., 1.0, 0.0, 0.0],
        [0.6, 0, 6, ..., 1.0, 0.0, 0.0],
        [1.0, 0, 11, ..., 1.0, 0.0, 0.0]], dtype=object)

In [15]:
Target_Vector

array([ 1,  1,  1, ..., -1, -1, -1])

## Start Training SVM

In [16]:
from sklearn.svm import SVC,LinearSVR
from sklearn.metrics import accuracy_score

In [30]:
clf = SVC(max_iter=30000,cache_size=3000,class_weight='balanced')
clf.fit(Final_Matrix, Target_Vector)
Predict_Y = clf.predict(Final_Matrix)
accuracy_score(Target_Vector,Predict_Y)

/usr/local/lib/python3.6/site-packages/sklearn/svm/base.py:220: ConvergenceWarning: Solver terminated early (max_iter=30000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


1.0

In [29]:
clf2 = SVC(kernel='linear',max_iter=1000000,cache_size=3000,class_weight='balanced')
clf2.fit(Final_Matrix, Target_Vector)
Predict_Y2 = clf2.predict(Final_Matrix)
accuracy_score(Target_Vector,Predict_Y2)

/usr/local/lib/python3.6/site-packages/sklearn/svm/base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


0.47022772724340367

In [1]:
print('test')

test
